[font]
size = 13.0

[font.normal]
# family = "JetBrainsMono Nerd Font"
# style = "Regular"

[window]
# padding = { x = 8, y = 8 }
opacity = 0.8

[colors.primary]
# background = "#1e1e2e"
# foreground = "#cdd6f4"
