# General settings
set -g history-limit 5000           # Increase scrollback buffer
set -g mouse on                    # Enable mouse support
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'egel/tmux-gruvbox'
# set -g prefix C-a                  # Use Ctrl-a as the prefix key
unbind C-b                         # Unbind the default prefix key
set-option -g prefix Tab
bind Tab send-prefix

# Appearance
set -g status-bg black             # Status bar background
set -g status-fg green             # Status bar foreground
set -g status-interval 5           # Refresh status bar every 5 seconds
# setw -g window-status-current-bg blue
# Keybindings
bind r source-file ~/.tmux.conf \; display "tmux reloaded"

# splite panes
bind '/' split-window -h
bind ';' split-window -v

# vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Remap Alt + [,] to switch to the previous,next window
bind -n M-[ previous-window
bind -n M-] next-window

# kill window using j
bind-key p confirm-before -p "Kill window? (y/n)" kill-window

#prefix(Tab) + n for rename window
bind-key i command-prompt -p "Rename window: " "rename-window '%%'"

#c=> create new window

#s for rename session
bind s command-prompt -p "Rename session: " "rename-session '%%'"

#h for new session
bind-key n command-prompt -p "Enter session name: " "new-session -s '%%'"

#show session and window and switch
bind t display-popup -E -x 35 -y 25 "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | cat <(tmux display-message -p '#S') - | fzf --reverse | xargs tmux switch-client -t"
bind u display-popup -E -x 35 -y 25 "tmux list-windows | fzf --reverse --with-nth=2 --delimiter=':' | awk -F: '{print \$1}' | xargs -I{} tmux select-window -t {}"

# Set the length of the left status bar so that i can give more lentht to sessinName
set-option -g status-left-length 40
run '~/.tmux/plugins/tpm/tpm'
